logging:
  level:
    root:
    org.springframework:
        web: INFO
        env.PropertySourcesPropertyResolver: DEBUG
server:
  port: 8080

spring:
  profiles:
    active: development
  jpa:
    show_sql: true
    defer-datasource-initialization: true
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=educate;trustServerCertificate=true
    username: sa
    password: raha
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8
    servlet:
      content-type: text/html
